[feature] Adding global sort order options
raphiniert-com/ra-data-postgrest pull request #125
Opened 2024-02-28 00:40 UTC by kav

Adding sort orders options. They are a bit verbose but do explain themselves rather well. I can update docs but given it's an optional param I didn't want to confuse new users in the initial example. Also added a test that covers all cases. In the event a user selects an order that matches postgres natural sorting we don't append the null ordering param to keep behavior consistant with existing functionality.

2024-02-28 11:36 UTC, scheiblr commented
Tank you very much. The code looks good to me. 
Although, it is a more advanced feature, I would recommend to document it in a specific section at the bottom of the readme. What do you think?

If not already done, please apply prettier.

2024-02-28 11:58 UTC, scheiblr approved these changes

2024-02-28 16:52 UTC, kav commented
I reverted my prettier run as it updated a bunch of unrelated changes but I'll give it a go and let you take a look, also adding docs at the bottom of the readme

2024-03-16 18:04 UTC, scheiblr requested changes
please change the href in `Postgrest supports specifying the position of nulls in sort [Ordering](https://postgrest.org/en/v12/references/api/tables_views.html#ordering). This can be configured via an optional data provider parameter:`  and let it link [sort ordering]. Thanks.

2024-03-19 13:02 UTC, scheiblr approved these changes
Thank you very much for the effort, looks good to me!

2024-03-19 13:06 UTC, merged